### ISSUE TITLE
这个项目是否还在维护更新呢？

### ISSUE THREAD

**Issue by bosen365** [ctripcorp/kbear#1]
您好 @koqizhao   请问Kbear这个项目当前还在维护更新吗？我看最近一次是在10个月前维护的

**Comment by koqizhao** [comment]
暂时没有维护。
我去年换工作了，比较忙。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bosen365** [comment]
您好，在源码里 “ com.ctrip.framework.kbear.service “ 这个包为何全源码里没有找到呀，想基于您的代码做一个定制开发做多集群版本的管理，请指点一下，非常感谢

**Comment by bosen365** [comment]
类似这个项目的开源项目有哪些，请指点一二，非常感谢

**Comment by koqizhao** [comment]
有些代码是在编译时从proto文件生成的。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by koqizhao** [comment]
我的其它项目https://github.com/mydotey下面。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
