### ISSUE TITLE
Double-Checked Locking

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [ctripcorp/kbear#6]
https://github.com/ctripcorp/kbear/blob/05ce21943636e3100a410b0ee4af7aef4e0b55fa/java/kbear-client/src/main/java/com/ctrip/framework/kbear/client/ConsumerProxy.java#L572-L586

Double-Checked Locking is widely cited and used as an efficient method for implementing lazy initialization in a multithreaded environment.
Unfortunately, it will not work reliably in a platform independent way when implemented in Java, without additional synchronization.
Declare a volatile local variable consumerHolder offers a much more elegant solution

**Comment by koqizhao** [comment]
Boring and useless advice!
